"""empty message

Revision ID: 1e2cea6da528
Revises: None
Create Date: 2015-12-16 10:00:06.202120

"""

# revision identifiers, used by Alembic.
revision = '1e2cea6da528'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme', sa.Column('slug', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'programme', ['slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programme', type_='unique')
    op.drop_column('programme', 'slug')
    ### end Alembic commands ###
