"""empty message

Revision ID: 22059c8154eb
Revises: 1e2cea6da528
Create Date: 2015-12-17 11:26:55.600439

"""

# revision identifiers, used by Alembic.
revision = '22059c8154eb'
down_revision = '1e2cea6da528'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'programme', 'user', ['user'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programme', type_='foreignkey')
    op.drop_column('programme', 'user')
    ### end Alembic commands ###
